import RPi.GPIO as GPIO

SERVO_PIN = 13
SERVO_FREQUENCY = 50
DUTY_CYCLE = 6

GPIO.setmode(GPIO.BOARD)
GPIO.setup(SERVO_PIN, GPIO.OUT)
CONTROL_PIN = GPIO.PWM(SERVO_PIN, SERVO_FREQUENCY)
CONTROL_PIN.start(DUTY_CYCLE)
CONTROL_PIN.ChangeDutyCycle(6.1)

input()


